# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Minisys-1A/Minisys-1A.srcs/sources_1/ip/divu/divu.xci
# IP: The module: 'divu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Minisys-1A/Minisys-1A.srcs/sources_1/ip/divu/divu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divu'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Minisys-1A/Minisys-1A.srcs/sources_1/ip/divu/divu.xci
# IP: The module: 'divu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Minisys-1A/Minisys-1A.srcs/sources_1/ip/divu/divu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divu'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
